### ISSUE TITLE
Print Resume After Power-Failure Not Functioning

### ISSUE THREAD

**Issue by jlwainwright** [Desuuuu/Marlin#1]
Printer: Creality CR10s-Pro V2

Firmware: https://github.com/Desuuuu/Marlin

System Board: Creality 3D v2.4

Issue: No Prompt To Resume Print After Restoring Power After Power Failure

Result Of M413 Echo:
"Power-loss recovery ON"

**Comment by Desuuuu** [comment]
Did you have an SD card inserted? The print progress is saved on the SD card so it's required for PLR to function.

I don't think that's an issue upstream because PLR appears to work for some people on 2.0.5.3.

It might take me some time to track this issue down because I'm waiting for parts for an upgrade, so I can't test this myself at the moment.

**Comment by jlwainwright** [comment]
The testing was done while printing from SD yes @Desuuuu 

Thank You.

**Comment by Desuuuu** [comment]
The latest version based on Marlin 2.0.6 contains some fixes related to PLR.

I suggest giving it a try, it might have actually solved the issue.
